[package]
name = "coreutilsp"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
parking_lot = "0.12.4"
clap = { version = "4.5", features = ["derive"] }
crossbeam-deque = "0.8"
rayon = "1.11"
filesize = "0.2"
nom = "8.0"
